name: Magento 2.4.8 CI

on:
  push:
    branches:
      - main

jobs:
  build-magento:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: mbstring, intl, pdo_mysql, soap, xsl, zip
          ini-values: post_max_size=256M, memory_limit=4G

       - name: Add Magento Authentication
        run: |
          echo '{
            "http-basic": {
              "repo.magento.com": {
                "username": "'"${{ secrets.MAGENTO_PUBLIC_KEY }}"'",
                "password": "'"${{ secrets.MAGENTO_PRIVATE_KEY }}"'"
              }
            }
          }' > ~/.composer/auth.json


      - name: Install Composer Dependencies
        run: composer install --no-dev --prefer-dist --no-interaction

      - name: DI Compile
        run: php bin/magento setup:di:compile

      - name: Magento Code Sniff
        run: |
          composer require magento/magento-coding-standard --dev
          vendor/bin/phpcs --standard=Magento2 app/code || true

      - name: PHPUnit Tests
        run: php vendor/bin/phpunit || true